/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_of_code

import kotlin.test.Test
import kotlin.test.assertEquals

class Day01Test {

    @Test fun partOne() {
        assertEquals(2, FuelUpper.fuelForMass(12))
        assertEquals(2, FuelUpper.fuelForMass(14))
        assertEquals(654, FuelUpper.fuelForMass(1969))
        assertEquals(33583, FuelUpper.fuelForMass(100756))

        assertEquals(3282386, FuelUpper.fuelForSpaceship(Spaceship))
    }

    @Test fun partTwo() {
        assertEquals(2, RocketEquationDoubleChecker.fuelForModule(14))
        assertEquals(966, RocketEquationDoubleChecker.fuelForModule(1969))
        assertEquals(50346, RocketEquationDoubleChecker.fuelForModule(100756))

        assertEquals(4920708, RocketEquationDoubleChecker.fuelForSpaceship(Spaceship))
    }

}

