/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_of_code

import kotlin.test.Test
import kotlin.test.assertEquals

class Day01Test {

    @Test fun partOne() {
        assertEquals(Fuel(2), FuelUpper.calculateFuelNeeded(Module(12)))
        assertEquals(Fuel(2), FuelUpper.calculateFuelNeeded(Module(14)))
        assertEquals(Fuel(654), FuelUpper.calculateFuelNeeded(Module(1969)))
        assertEquals(Fuel(33583), FuelUpper.calculateFuelNeeded(Module(100756)))

        assertEquals(Fuel(3282386), FuelUpper.calculateFuelNeeded(Spaceship))
    }

    @Test fun partTwo() {
        assertEquals(Fuel(2), RocketEquationDoubleChecker.calculateFuelNeeded(Module(14)))
        assertEquals(Fuel(966), RocketEquationDoubleChecker.calculateFuelNeeded(Module(1969)))
        assertEquals(Fuel(50346), RocketEquationDoubleChecker.calculateFuelNeeded(Module(100756)))

        assertEquals(Fuel(4920708), RocketEquationDoubleChecker.calculateFuelNeeded(Spaceship))
    }

}

